## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# Sets user-defined palette
palette = "dark_decay"

# Setups
#format="$directory$git_branch$character"
format="$directory$git_branch"
#right_format = """$git_status$cmd_duration"""
right_format = """$character"""
add_newline = false

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = false
java.disabled = true
golang.disabled = true

[conda]
format = ' [$symbol$environment](dimmed green) '

# Prompt symbols 
[character]
success_symbol = "[ ](green bold)"
error_symbol = "[ ](red)"
vicmd_symbol = "[](peach)"

[directory]
format = "[]($style)[󰉋 ](bg:blue fg:background)[$path](bg:blue fg:background bold)[ ]($style)"
style = "bg:none fg:blue"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[]($style)[[ ](bg:blue fg:background bold)$branch](bg:blue fg:background)[ ]($style)"
style = "bg:none fg:blue"

[git_status]
# $all status$ahead_behind
format = "[]($style)[$all_status$ahead_behind](bg:base fg:yellow)[ ]($style)"
style = "bg:none fg:base"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[神](bg:base fg:flamingo bold)$duration](bg:base fg:text)[ ]($style)"
disabled = false
style = "bg:none fg:base"

[palettes.dark_decay]
background = "#101419"
foreground = "#b6beca"
red = "#e05f65"
green = "#78dba9"
yellow = "#f1cf8a"
blue = "#70a5eb"
magenta = "#c68aee"